###############################################################
# Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

name: "policy-hub"

# -- Provide centralidp base address (CX IAM), without trailing '/auth'.
centralidpAddress: "https://centralidp.example.org"

ingress:
  # -- Policy Hub ingress parameters,
  # enable ingress record generation for policy-hub.
  enabled: false
  name: "policy-hub"
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    # -- Provide CORS allowed origin.
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://*.example.org"
  tls:
    # -- Provide tls secret.
    - secretName: ""
      # -- Provide host for tls secret.
      hosts:
        - "policy-hub.example.org"
  hosts:
    # -- Provide default path for the ingress record.
    - host: "policy-hub.example.org"
      paths:
        - path: "/api/policy-hub"
          pathType: "Prefix"
          backend:
            service: "policy-hub-service"
            port: 8080
dotnetEnvironment: "Production"
dbConnection:
  schema: "hub"
  sslMode: "Disable"

keycloak:
  central:
    authRealm: "CX-Central"
    jwtBearerOptions:
      requireHttpsMetadata: "true"
      metadataPath: "/auth/realms/CX-Central/.well-known/openid-configuration"
      tokenValidationParameters:
        validIssuerPath: "/auth/realms/CX-Central"
        validAudience: "Cl23-CX-Policy-Hub"
      refreshInterval: "00:00:30"
    tokenPath: "/auth/realms/CX-Central/protocol/openid-connect/token"
    # -- Flag if the api should be used with an leading /auth path
    useAuthTrail: true
healthChecks:
  startup:
    path: "/health/startup"
  liveness:
    path: "/healthz"
  readyness:
    path: "/ready"

policyhub:
  name: "policy-hub-service"
  image: "tractusx/policy-hub-service:0.1.0-rc.1"
  # -- We recommend not to specify default resource limits and to leave this as a conscious choice for the user.
  # If you do want to specify resource limits, uncomment the following lines and adjust them as necessary.
  resources:
    requests:
      cpu: 15m
      memory: 300M
    # limits:
    #   cpu: 45m
    #   memory: 400M
  logging:
    businessLogic: "Information"
    default: "Information"
  healthChecks:
    startup:
      tags:
      - name: "HEALTHCHECKS__0__TAGS__1"
        value: "policyhubdb"
  swaggerEnabled: false

policyhubmigrations:
  name: "policy-hub-migrations"
  image: "tractusx/policy-hub-migrations:0.1.0-rc.1"
  # -- We recommend not to specify default resource limits and to leave this as a conscious choice for the user.
  # If you do want to specify resource limits, uncomment the following lines and adjust them as necessary.
  resources:
    requests:
      cpu: 15m
      memory: 105M
    # limits:
    #   cpu: 45m
    #   memory: 105M
  seeding:
    testDataEnvironments: ""
    testDataPaths: "Seeder/Data"
  logging:
    default: "Information"

postgresql:
  # -- PostgreSQL chart configuration;
  # default configurations:
  # host: "policy-hub-postgresql-primary",
  # port: 5432;
  # Switch to enable or disable the PostgreSQL helm chart.
  enabled: true
  auth:
    # -- Non-root username.
    username: hub
    # -- Database name.
    database: policy-hub
    # -- Secret containing the passwords for root usernames postgres and non-root username hub.
    existingSecret: "{{ .Release.Name }}-phub-postgres"
  architecture: replication
  audit:
    pgAuditLog: "write, ddl"
    logLinePrefix: "%m %u %d "
  primary:
    # -- Extended PostgreSQL Primary configuration (increase of max_connections recommended - default is 100)
    extendedConfiguration: ""
    initdb:
      scriptsConfigMap: "{{ .Release.Name }}-phub-cm-postgres"
  readReplicas:
  # -- Extended PostgreSQL read only replicas configuration (increase of max_connections recommended - default is 100)
    extendedConfiguration: ""

externalDatabase:
  # -- External PostgreSQL configuration
  # IMPORTANT: non-root db user needs to be created beforehand on external database.
  # And the init script (02-init-db.sql) available in templates/configmap-postgres-init.yaml
  # needs to be executed beforehand.
  # Database host ('-primary' is added as postfix).
  host: "phub-postgres-ext"
  # -- Database port number.
  port: 5432
  # -- Non-root username for policy-hub.
  user: "hub"
  # -- Database name.
  database: "policy-hub"
  # -- Password for the non-root username (default 'hub'). Secret-key 'password'.
  password: ""
  # -- Secret containing the password non-root username, (default 'hub').
  existingSecret: "policy-hub-external-db"
  # -- Name of an existing secret key containing the database credentials.
  existingSecretPasswordKey: "password"

secrets:
  postgresql:
    auth:
      existingSecret:
        # -- Password for the root username 'postgres'. Secret-key 'postgres-password'.
        postgrespassword: ""
        # -- Password for the non-root username 'hub'. Secret-key 'password'.
        password: ""
        # -- Password for the non-root username 'repl_user'. Secret-key 'replication-password'.
        replicationPassword: ""

portContainer: 8080

portService: 8080

replicaCount: 3

# -- Node labels for pod assignment
nodeSelector: {}

# -- Tolerations for pod assignment
tolerations: []

affinity:
# -- Following Catena-X Helm Best Practices,
# [reference](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity).
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: DoesNotExist
          topologyKey: kubernetes.io/hostname

updateStrategy:
# -- Update strategy type,
# rolling update configuration parameters,
# [reference](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies).
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

# -- Following Catena-X Helm Best Practices,
# [reference](https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L210).
startupProbe:
  failureThreshold: 30
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
